# Generated by Django 4.0.6 on 2022-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorii', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name'], 'verbose_name': 'POsty', 'verbose_name_plural': 'Posts'},
        ),
    ]
