# Generated by Django 4.0.6 on 2022-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorii', '0004_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='amount_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=50),
        ),
    ]
